Repository netguru-code-college/vol4-alpaca, pull requests merged in 2019-02, with the labels that each got.

#1 Add Rubocop gem and run on code
  Gemfile
  Gemfile.lock
  Rakefile
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/controllers/application_controller.rb
  app/helpers/application_helper.rb
  app/jobs/application_job.rb
  app/mailers/application_mailer.rb
  app/models/application_record.rb
  bin/bundle
  bin/rails
  bin/rake
  bin/setup
  bin/spring
  bin/update
  bin/yarn
  config.ru
  config/application.rb
  config/boot.rb
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/application_controller_renderer.rb
  config/initializers/assets.rb
  config/initializers/backtrace_silencers.rb
  config/initializers/content_security_policy.rb
  config/initializers/cookies_serializer.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/initializers/mime_types.rb
  config/initializers/session_store.rb
  config/initializers/to_time_preserves_timezone.rb
  config/initializers/wrap_parameters.rb
  config/puma.rb
  config/routes.rb
  config/spring.rb
  db/seeds.rb
Labels: checked

#2 Add and configure Devise gem
  Gemfile
  Gemfile.lock
  app/views/layouts/application.html.erb
  config/environments/development.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
Labels: checked

#5 Add Faker gem
  Gemfile
  Gemfile.lock
Labels: waiting

#12 Alpaca model, Google Custom Search API integration
  Gemfile.lock
  app/models/alpaca.rb
  app/models/concerns/api_helper.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  db/migrate/20190216142309_create_alpacas.rb
  db/schema.rb
  spec/models/alpaca_spec.rb
Labels: waiting

#13 Dashboard view
  app/assets/images/events.jpg
  app/assets/images/welcome.jpg
  app/assets/stylesheets/application.scss
  app/controllers/home_controller.rb
  app/views/home/dashboard.html.haml
  app/views/home/welcome.html.haml
  config/routes.rb
Labels: checked, waiting

#15 Install pundtid gem
  Gemfile
  Gemfile.lock
  app/policies/application_policy.rb
Labels: waiting

#26 Alpaca and Google Custom Search services
  app/models/alpaca.rb
  app/services/alpaca_service.rb
  app/services/google_custom_search_api_service.rb
  spec/models/alpaca_spec.rb
Labels: waiting

#55 Event functionality
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/events.scss
  app/assets/stylesheets/footer.scss
  app/controllers/events_controller.rb
  app/helpers/events_helper.rb
  app/models/alpaca.rb
  app/models/event.rb
  app/services/calculate_event_points_and_assign_to_alpacas.rb
  app/views/events/_alpaca_card.html.haml
  app/views/events/_form.html.haml
  app/views/events/_listing.html.haml
  app/views/events/index.html.haml
  app/views/events/new.html.haml
  app/views/events/show.html.haml
  app/views/home/dashboard.html.haml
  app/views/layouts/application.html.haml
  app/views/layouts/shared/_navigation.html.haml
  config/routes.rb
  db/schema.rb
Labels: checked
